### ISSUE TITLE
The different between xyz and xyz2_feat2

### ISSUE THREAD

**Issue by yeminglang** [hrzhou2/AdaptConv-master#10]
Dear authors,
I notice that `adaptive_feature = 'xyz'` is selected for training, but according to you paper, it is `adaptive_feature = 'xyz2_feat2'` that should be used. By the way, it seems that `adaptive_feature = 'asmy'` never be used, because you chose `if self.feat_mode == 'asym':` rather than `if 'asym' in self.feat_mode:` in the code, and I think  `adaptive_feature = 'asmy'` can't be use for its own. Maybe I do not get your idea... Can you please evaluate whether what I said is correct?

我注意到你们选择了 `adaptive_feature = 'xyz'` 进行训练，但根据你的论文，应该使用的是 `adaptive_feature = 'xyz2_feat2'`。还有个小问题，似乎从未使用过 `adaptive_feature = 'asmy'`，因为您在代码中选择了 `if self.feat_mode == 'asym':` 而不是 `if 'asym' in self.feat_mode:`，因此我觉得 `adaptive_feature = 'asmy'` 不能单独使用（xyz和feat2就表示不了了）。也许我没很好地理解你们的想法......你能评估一下我说的是否正确吗？

Thanks.

Regards

**Comment by hrzhou2** [comment]
Yes, 'asym' is the original asymmetric feature and is equal to 'xyz2_feat2'. You can use either of them. Also, these are architecture designs that are all suitable for building an adaptive conv layer. This is the reason why we set up such a feature type argument.

**Comment by yeminglang** [comment]
Thank you! Have a nice day!
